@extends('layouts.web')

@section('title', 'Stedigate.COM - Term of Use')

@section('content')

    <div class="grid gap-6 lg:gap-8">
        <div class="flex items-start gap-4 rounded-lg bg-white p-6 shadow-[0px_14px_34px_0px_rgba(0,0,0,0.08)] ring-1 ring-white/[0.05] transition duration-300 hover:text-black/70 hover:ring-black/20 focus:outline-none focus-visible:ring-[#FF2D20] lg:pb-10 dark:bg-zinc-900 dark:ring-zinc-800 dark:hover:text-white/70 dark:hover:ring-zinc-700 dark:focus-visible:ring-[#FF2D20]">
            <div class="flex size-12 shrink-0 items-center justify-center rounded-full bg-[#9340E4]/10 sm:size-16">
                <svg class="size-9 sm:size-10" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 5 45 41">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><defs><style>.cls-1{fill:#231f20;}.cls-2{fill:#bf9ae5;}.cls-3{fill:#9340E4;}.cls-4{fill:#9340E4;}</style></defs><title></title><path class="cls-1" d="M44.693,41.394,35.38,32.607l2.52-2.52.036.036a1.671,1.671,0,0,0,2.36,0l.656-.655a1.674,1.674,0,0,0,0-2.36L33.5,19.654a1.718,1.718,0,0,0-.277-.222V7a2.5,2.5,0,0,0-2.5-2.5H7A2.5,2.5,0,0,0,4.5,7V43A2.5,2.5,0,0,0,7,45.5H30.72a2.5,2.5,0,0,0,2.5-2.5V36.03l8.173,8.663a2.335,2.335,0,0,0,1.657.807h.029a2.338,2.338,0,0,0,1.614-4.106Z"></path><path class="cls-2" d="M30.72,44.5H28.64a2.574,2.574,0,0,0-2.546-2.263h-.027A2,2,0,0,0,24.075,40.3H13.644a2,2,0,0,0-1.991,1.938h-.027A2.573,2.573,0,0,0,9.08,44.5H7A1.5,1.5,0,0,1,5.5,43V7A1.5,1.5,0,0,1,7,5.5H30.72A1.5,1.5,0,0,1,32.22,7V19.175a1.656,1.656,0,0,0-1.082.479l-.655.656a1.667,1.667,0,0,0,0,2.359l.036.037L23,30.229l-.037-.036a1.669,1.669,0,0,0-2.359,0l-.655.656a1.667,1.667,0,0,0,0,2.359L27.4,40.662a1.668,1.668,0,0,0,2.36,0l.655-.655a1.672,1.672,0,0,0,0-2.36l-.036-.036,1.844-1.844V43A1.5,1.5,0,0,1,30.72,44.5Z"></path><path class="cls-1" d="M10.863,12.761H26.857a.5.5,0,0,0,0-1H10.863a.5.5,0,0,0,0,1Z"></path><path class="cls-1" d="M10.863,18.307H26.857a.5.5,0,0,0,0-1H10.863a.5.5,0,0,0,0,1Z"></path><path class="cls-1" d="M10.863,23.854H26.857a.5.5,0,0,0,0-1H10.863a.5.5,0,0,0,0,1Z"></path><path class="cls-1" d="M10.863,29.4H20.07a.5.5,0,0,0,0-1H10.863a.5.5,0,0,0,0,1Z"></path><path class="cls-1" d="M18.77,33.946H10.863a.5.5,0,0,0,0,1H18.77a.5.5,0,0,0,0-1Z"></path><rect class="cls-3" height="8.439" transform="translate(-12.407 30.363) rotate(-45)" width="10.641" x="25.127" y="25.939"></rect><path class="cls-4" d="M29.705,38.354a.669.669,0,0,1,0,.946l-.655.655a.684.684,0,0,1-.946,0L20.651,32.5a.668.668,0,0,1,0-.945l.655-.656a.67.67,0,0,1,.945,0Z"></path><path class="cls-4" d="M40.245,27.815a.671.671,0,0,1,0,.946l-.656.655a.67.67,0,0,1-.946,0L31.19,21.962a.668.668,0,0,1,0-.945l.655-.656a.67.67,0,0,1,.945,0Z"></path><path class="cls-3" d="M26.094,43.237A1.582,1.582,0,0,1,27.64,44.5H10.08a1.581,1.581,0,0,1,1.546-1.263Z"></path><path class="cls-3" d="M12.659,42.237a.991.991,0,0,1,.985-.938H24.075a.992.992,0,0,1,.986.938Z"></path><path class="cls-4" d="M44.035,44.035a1.321,1.321,0,0,1-.971.465,1.347,1.347,0,0,1-.943-.493l-8.806-9.334,1.358-1.358,9.334,8.806a1.351,1.351,0,0,1,.493.943A1.406,1.406,0,0,1,44.035,44.035Z"></path></g>
                </svg>
            </div>

            <div class="pt-3 sm:pt-5 text-gray-900 dark:text-gray-300">
                <h2 class="text-xl font-semibold text-black dark:text-white">Term of use</h2>
                <p class="mt-4 text-sm/relaxed">
                    Last updated: 2024-01-01
                </p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">1. Introduction</h3>
                <p class="mt-4 text/relaxed">Please read these terms and conditions carefully before using Our Service.<br>
                    The words of which the initial letter is capitalized have meanings defined under the following conditions.<br>
                    The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">2. Definitions</h3>
                <p class="mt-4 text/relaxed">For the purposes of these Terms and Conditions:</p>
                <ul>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with the Company, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to <span>Stedigate affiliate.</span></li>
                    <li><strong>Country</strong> refers to: Republic of Cyprus.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Terms and Conditions</strong> (also referred as “Terms”) mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service.</li>
                    <li><strong>Third-party Social Media Service</strong> means any services or content (including data, information, products or services) provided by a third party that may be displayed, included or made available by the Service.</li>
                    <li><strong>Website</strong> refers to Stedigate, accessible from stedigate.com</li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">3. Acknowledgement</h3>
                <p class="mt-4 text/relaxed">These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
                <p class="mt-4 text/relaxed">The information contained herein is for general information purposes only. We endeavour to keep the information up to date and correct, however We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the Service or the information, products, services, or related graphics contained on the Service for any purpose. Any reliance You place on such information is therefore strictly at Your own risk.</p>
                <p class="mt-4 text/relaxed">Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
                <p class="mt-4 text/relaxed">By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.</p>
                <p class="mt-4 text/relaxed">Your access to and use of the Service is also conditioned on Your acceptance of and acknowledgement of the Privacy Policy and the Cookie Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Service or the Website and tells You about Your privacy rights and how the law protects You. Our Cookie Policy sets out information about the cookies on Our Service. Please read Our Privacy Policy and Cookie Policy carefully before using Our Service.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">4. Links to Other Websites</h3>
                <p class="mt-4 text/relaxed">Our Service may contain links to third-party websites or services that are not owned or controlled by the Company.</p>
                <p class="mt-4 text/relaxed">The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
                <p class="mt-4 text/relaxed">We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">5. Intellectual property rights</h3>
                <p class="mt-4 text/relaxed">We are the owner or the licensee of all intellectual property rights in Our Service, and in the material published on it. Those works are protected by copyright laws and treaties around the world. All such rights are reserved.</p>
                <p class="mt-4 text/relaxed">You must not use any part of the content on Our Service for commercial purposes without obtaining a license to do so from Us.</p>
                <p class="mt-4 text/relaxed">If You print off, copy or download any part of Our Service in breach of these Terms, Your right to use Our Service will cease immediately and You must, at Our option, return or destroy any copies of the materials You have made.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">6. Termination</h3>
                <p class="mt-4 text/relaxed">We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.<br>
                    Upon termination, Your right to use the Service will cease immediately.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">7. Limitation of Liability</h3>
                <p class="mt-4 text/relaxed">Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to 100 EUR.</p>
                <p class="mt-4 text/relaxed">To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
                <p class="mt-4 text/relaxed">We will not be liable for any loss or damage caused by a virus, distributed denial-of-service attack, or other technologically harmful material that may infect Your computer equipment, computer programs, data or other proprietary material due to Your use of Our Service or to Your downloading of any content on it, or on any website linked to it.</p>
                <p class="mt-4 text/relaxed">Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party’s liability will be limited to the greatest extent permitted by law.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">8. Disclaimer</h3>
                <p class="mt-4 text/relaxed">The Service is provided to You “AS IS” and “AS AVAILABLE” and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
                <p class="mt-4 text/relaxed">Without limiting the foregoing, neither the Company nor any of the company’s provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
                <p class="mt-4 text/relaxed">Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">9. Governing Law</h3>
                <p class="mt-4 text/relaxed">The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Service may also be subject to other local, state, national, or international laws.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">10. Dispute Resolution</h3>
                <p class="mt-4 text/relaxed">If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.</p>
                <p class="mt-4 text/relaxed"><span style="text-decoration: underline;">For European Union (EU) Users</span></p>
                <p class="mt-4 text/relaxed">If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which you are resident in.</p>
                <p class="mt-4 text/relaxed"><span style="text-decoration: underline;">United States Legal Compliance</span></p>
                <p class="mt-4 text/relaxed">You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a “terrorist supporting” country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">11. Severability</h3>
                <p class="mt-4 text/relaxed">If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">12. Waiver</h3>
                <p class="mt-4 text/relaxed">Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Terms shall not effect a party’s ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute a waiver of any subsequent breach.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">13. Changes to these Terms and Conditions</h3>
                <p class="mt-4 text/relaxed">We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. Please check this page from time to time to take notice of any changes We made, as they are binding on You.</p>
                <p class="mt-4 text/relaxed">By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.</p>
                <h3 class="text-xl font-semibold text-black dark:text-white mt-4">14. Contact Us</h3>
                <p class="mt-4 text/relaxed">If you have any questions about these Terms and Conditions, You can contact us by email <a href="mailto:info@stedigate.com">info@stedigate.com</a></p>
            </div>
        </div>
    </div>
@endsection
